import './../models/appointment.dart';

// this would be loaded from API call from server each day, and updated back to server on each change of appointment

List<Appointment> APPOINTMENT_DATA = [
  Appointment(
    id: 1,
    isBooked: true,
    apptTime: '8:00-8:30',
    phoneNumber: '(214) 724-0609',
    name: 'Paul McNeme',
    lessons: 2,
  ),
  Appointment(
    id: 2,
    isBooked: false,
    apptTime: '8:30-9:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 3,
    isBooked: false,
    apptTime: '9:00-9:30',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 4,
    isBooked: true,
    apptTime: '9:30-10:00',
    phoneNumber: '(214) 867-5309',
    name: 'Jenny',
    lessons: 0,
  ),
  Appointment(
    id: 5,
    isBooked: false,
    apptTime: '10:00-10:30',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 6,
    isBooked: false,
    apptTime: '10:30-11:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 7,
    isBooked: false,
    apptTime: '11:00-11:30',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 8,
    isBooked: false,
    apptTime: '11:30-12:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 9,
    isBooked: true,
    apptTime: '12:00-12:30',
    phoneNumber: '(214) 489-4608',
    name: 'Alicia Keys',
    lessons: 90,
  ),
  Appointment(
    id: 10,
    isBooked: false,
    apptTime: '12:30-1:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 11,
    isBooked: false,
    apptTime: '1:00-1:30',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 12,
    isBooked: false,
    apptTime: '1:30-2:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 13,
    isBooked: false,
    apptTime: '2:00-2:30',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 14,
    isBooked: false,
    apptTime: '2:30-3:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 15,
    isBooked: false,
    apptTime: '3:00-3:30',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 16,
    isBooked: false,
    apptTime: '3:30-4:00',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
];
