import './../models/appointment.dart';

// this would be loaded from API call from server each day, and updated back to server on each change of appointment

List<Appointment> APPOINTMENT_DATA = [
  Appointment(
    id: 1,
    isBooked: true,
    apptTime: '0800-0830',
    phoneNumber: '(214) 724-0609',
    name: 'Paul McNeme',
    lessons: 2,
  ),
  Appointment(
    id: 2,
    isBooked: false,
    apptTime: '0830-0900',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 3,
    isBooked: false,
    apptTime: '0900-0930',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 4,
    isBooked: true,
    apptTime: '0930-1000',
    phoneNumber: '(214) 867-5309',
    name: 'Jenny',
    lessons: 0,
  ),
  Appointment(
    id: 5,
    isBooked: false,
    apptTime: '1000-1030',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 6,
    isBooked: false,
    apptTime: '1030-1100',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 7,
    isBooked: false,
    apptTime: '1100-1130',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 8,
    isBooked: false,
    apptTime: '1130-1200',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 9,
    isBooked: true,
    apptTime: '1200-1230',
    phoneNumber: '(214) 489-4608',
    name: 'Alicia Keys',
    lessons: 90,
  ),
  Appointment(
    id: 10,
    isBooked: false,
    apptTime: '1230-1300',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 11,
    isBooked: false,
    apptTime: '1300-1330',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 12,
    isBooked: false,
    apptTime: '1330-1400',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 13,
    isBooked: false,
    apptTime: '1400-1430',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 14,
    isBooked: false,
    apptTime: '1430-1500',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 15,
    isBooked: false,
    apptTime: '1500-1530',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 16,
    isBooked: false,
    apptTime: '1530-1600',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 17,
    isBooked: false,
    apptTime: '1600-1630',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
  Appointment(
    id: 18,
    isBooked: false,
    apptTime: '1630-1700',
    phoneNumber: '',
    name: '',
    lessons: 0,
  ),
];
